import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";
import { defineConfig, globalIgnores } from "eslint/config";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// eslint-config-next@15.x ships its "core-web-vitals" / "typescript" presets
// in the legacy eslintrc (`extends`) format rather than as native flat-config
// arrays, so we bridge them via FlatCompat — this is the standard pattern
// documented by Next.js for using eslint-config-next under ESLint 9's flat
// config with Next.js 15.
const compat = new FlatCompat({
  baseDirectory: __dirname,
});

const eslintConfig = defineConfig([
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    rules: {
      // Guest-submitted names and ucapan are rendered on the public page.
      // React escapes interpolated text by default; dangerouslySetInnerHTML
      // bypasses that and would turn a submitted wish into stored XSS.
      "react/no-danger": "error",
      // Drizzle parameterises everything except `sql.raw`, which splices a
      // string straight into the statement. Never needed here.
      "no-restricted-syntax": [
        "error",
        {
          selector:
            "CallExpression[callee.object.name='sql'][callee.property.name='raw']",
          message:
            "sql.raw() bypasses parameterisation. Use Drizzle's query builder or the sql`` template.",
        },
      ],
    },
  },
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by @opennextjs/cloudflare / wrangler — never hand-edited.
    ".open-next/**",
    ".wrangler/**",
    "cloudflare-env.d.ts",
  ]),
]);

export default eslintConfig;
